Logic to handle file downloading during test execution changed
DevExpress/testcafe-legacy-api pull request #18
Opened 2016-10-06 10:25 UTC by helen-dikareva

It's require for https://github.com/DevExpress/testcafe/pull/855
/cc @AlexanderMoskovkin

2016-10-11 08:25 UTC, AlexanderMoskovkin requested changes

2016-10-11 08:25 UTC, AlexanderMoskovkin commented on src/test-run/command.js
> +    // NOTE: we need this message to support new page unload barier's mechanism
I think this comment is redundant. [this](https://github.com/DevExpress/testcafe-legacy-api/pull/18/files#diff-a21f56bee759db22062e32250e3df48cR161) is enough

2016-10-12 11:35 UTC, AlexanderMoskovkin approved these changes
lgtm

2016-10-12 11:36 UTC, helen-dikareva commented
/cc @AndreyBelym

2016-10-12 11:42 UTC, AndreyBelym approved these changes
lgtm

2016-10-12 11:44 UTC, merged